### PR TITLE
working on code readability

### PR DESCRIPTION
**Pull request by allain**
To that end:
- nesting has been lessened
- where I saw some expressions could be simplified, I did so
- reusing jQuery calls when called repeatedly

I've ensured that all unit tests are still passing.

Hopefully, you see value in this work. If not, no hard feelings, it was a way for me to develop a deeper understanding of what's going on.

Cheers

### CODE REVIEW

**Comment by carsongross** [comment]
Hey Allain, happy to take in refactorings and improvements.  Since it's such a big change it will take me a while to review (maybe this Friday if I have some free time) so don't worry if I don't merge it for a bit.

**Comment by allain** [comment]
Great. No problem.

**Comment by carsongross** [comment]
Hey Allain, I am beginning reviewing the change today.  It is pretty big, so it might take a while.  I did notice one subtle issue: 

          if (globalEval('(function (data, textStatus, xhr) {' + onSuccess + '})')(data, textStatus, xhr) == false) 

was changed to 

          if (!globalEval('(function (data, textStatus, xhr) {' + onSuccess + '})')(data, textStatus, xhr)) {

Which, if I understand correctly is a change in semantics.  Previously people would have to have returned 'false' explicitly.  In the new code, if they didn't return anything it would be interpreted as false and begin exiting.  Does that sound correct?

**Comment by allain** [comment]
in the previous code returning anything that evaluates to falsy would execute the if statement. so, '0', '', 0, would all be considered == false.

It was an attempt to make the loose check more explicit, but you are correct I've tried it out and undefined == false is false, and strangely undefined == true is also false. 

The safest option is to revert that change.

**Comment by allain** [comment]
reverted

**Comment by allain** [comment]
Want me to break this out into smaller PRs targetting more specific changes?

**Comment by carsongross** [comment]
That would be epically helpful.  :)

Can you do them against development, rather than master?

Cheers,
Carson

On February 16, 2016 at 3:14:48 PM, Allain Lalonde (notifications@github.com) wrote:

Want me to break this out into smaller PRs targetting more specific changes?

**Comment by allain** [comment]
ok. Will do.

**Comment by allain** [comment]
Seems dev branch is 10 days older than master. Mind updating it, then I'll begin.

**Pull request closed without merging**
