### PR TITLE
Updated Intercooler to support JS and modules.

### PR DESCRIPTION
**Pull request by OvermindDL1**
Commit log:

> Updated build system, NPM updated package.json itself, thus reformatting
> it as it was not in proper formatting before.
> 
> Fixed trailing spaces in intercooler.js as the linter was angry with it.
> 
> Brought in grunt-umd and set it up.
> 
> Bumped version number by patch as there should be no interface changes.
> 
> Ran unit tests, all passed except Coverage (which did not pass before
> either).
> 
> Ran local testing in ES6 babel system, tests passed.
> 
> Committing to GH to submit PR to upstream.

This should act identically to before for people that are already using it.

For module systems the only thing someone needs to do is make sure they have jquery in their own package.json as well as intercooler, I did not make intercooler depend on jQuery itself though you might want to add jQuery as a normal 'dependency' (with a `">= 1.10.0"` version requirement specifically) just to make sure.

To use it all that needs to be done in ES6 is just:
```javascript
import Intercooler from "intercooler";
```
And literally nothing else, it will auto-import their jquery that is already in the module system and all.

To use it all that needs to be done in AMD/CommonJS is just:
```javascript
var Intercooler = require("intercooler");
```
And literally nothing else, it will auto-import their jquery that is already in the module system and all.

To use it as normal, well, just use it as normal, it still exposes an `Intersteller` global object when brought into the global space (like via a `<script ..>` tag), so nothing changes there what-so-ever.

### CODE REVIEW

**Comment by carsongross** [comment]
Let me review this change tomorrow (sorry, busy tonight)

I don't understand a lot of what is going on (my build-foo is weak and my javascript build-foo is, studiously, nil) so I want to walk through it all.

In the meantime can you change the target branch to be development?

**Comment by OvermindDL1** [comment]
> Let me review this change tomorrow (sorry, busy tonight)

Know how that goes.  :-)

> I don't understand a lot of what is going on (my build-foo is weak and my javascript build-foo is, studiously, nil) so I want to walk through it all.

Mine... used to be poor but is increasing lately (work) sadly...  I really do not like javascript...  >.>

> In the meantime can you change the target branch to be development?

Retargeted to the 'development' branch, however github added a lot of apparently missing commits that master has that development did not, was that intended?

**Comment by jpmurray** [comment]
Just checking, but should it be working with Webpack? Using `require('intercooler)` finished in a `module not found` error.

**Comment by OvermindDL1** [comment]
> Just checking, but should it be working with Webpack? Using `require('intercooler)` finished in a `module not found` error.

It will as long as you use some packer, I think for webpack that is called browserfy or something like that (I'm much more used to brunch instead of webpack).  Without a packer then you just include it in your final app via a script tag as per normal usage.

**Comment by lmartins** [comment]
The package published on NPM is still throwing an error when trying to build it using something like Webpack. Is there any updates on this? Thank you.

**Comment by OvermindDL1** [comment]
> The package published on NPM is still throwing an error when trying to build it using something like Webpack. Is there any updates on this? Thank you.

It works fine in browserify here, do you have an example repo?

**Comment by lmartins** [comment]
Hi @OvermindDL1 I just had to add the main file to the package.json 
As soon as I did that Webpack then is able to make the build.

**Comment by OvermindDL1** [comment]
Ahh, that makes sense.  You should submit a PR.  :-)

**Comment by muralikg** [comment]
In the meantime you could use  `require('intercooler/src/intercooler.js');`

**Comment by carsongross** [comment]
I'd like to get a fix in for the next release (friday?)  

@OvermindDL1 do you understand the issue well enough to put in a fix?  I ain't touchin' that magic build malarky.

**Comment by OvermindDL1** [comment]
> @OvermindDL1 do you understand the issue well enough to put in a fix? I ain't touchin' that magic build malarky.

I can if you want, but it is quite easy to add in.  :-)

You'd just add this to the package.json file, say right under the `license` line or so:
```javascript
  "main": "dist/intercooler.js",
```

Otherwise if you want a PR for it just say and I can do so in the next day or so.  :-)

**Comment by carsongross** [comment]
I think even I can handle that much...

Thanks!

Cheers,
Carson


On January 31, 2017 at 2:21:31 PM, OvermindDL1 (notifications@github.com)
wrote:

@OvermindDL1 <https://github.com/OvermindDL1> do you understand the issue
well enough to put in a fix? I ain't touchin' that magic build malarky.

I can if you want, but it is quite easy to add in. :-)

You'd just add this to the package.json file, say right under the license
line or so:

  "main": "dist/intercooler.js",

Otherwise if you want a PR for it just say and I can do so in the next day
or so. :-)

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/pull/117#issuecomment-276512168>,
or mute the thread

**Comment by lmartins** [comment]
Sorry I missed @OvermindDL1 answer. @carsongross for Webpack all that was needed was in adding the main file to package.json as @OvermindDL1 suggests. Not sure about other build systems but I can only imagine to be the same.

**Comment by carsongross** [comment]
Please verify
https://github.com/LeadDyno/intercooler-js/commit/330fc6632e0f54e6873cffa4ad9f22c9893b20e7


On February 1, 2017 at 1:18:00 AM, Luis Martins (notifications@github.com)
wrote:

Sorry I missed @OvermindDL1 <https://github.com/OvermindDL1> answer.
@carsongross <https://github.com/carsongross> for Webpack all that was
needed was in adding the main file to package.json as @OvermindDL1
<https://github.com/OvermindDL1> suggests. Not sure about other build
systems but I can only imagine to be the same.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/pull/117#issuecomment-276608855>,
or mute the thread

**Pull request merged**
